In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [3]:
df =pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [6]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
df.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [8]:
X=df.drop('Outcome',axis=1)
Y =df['Outcome']

In [56]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
df_scaled= sc.fit_transform(X)
df_scaled

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
X =df_scaled
Y= df['Outcome']
print(X)
print(Y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.10, random_state=2, stratify=Y)

In [13]:
print(X.shape,X_train.shape,X_test.shape)

(768, 8) (691, 8) (77, 8)


MODEL TRAINING


In [14]:
svm_model =svm.SVC(kernel='linear')
svm_model.fit(X_train, Y_train)
Y_train_pred =svm_model.predict(X_train)
Y_test_pred =svm_model.predict(X_test)

In [15]:
score =accuracy_score(Y_train, Y_train_pred)
print(score)

#or alternate method

score1 = svm_model.score(X_train,Y_train)
print(score1)

0.784370477568741
0.784370477568741


In [16]:
score2 =accuracy_score(Y_test, Y_test_pred)
print(score2)

#or alternate method

score3 = svm_model.score(X_test,Y_test)
print(score3)

0.7792207792207793
0.7792207792207793


In [ ]:
# As it is diabetic prediction we can go with recall also as it is more suitable for this kinda data

In [17]:
from sklearn.metrics import recall_score
rec_score =recall_score(Y_train,Y_train_pred ,pos_label=1)
rec_score

0.5892116182572614

In [18]:
rec_score =recall_score(Y_test,Y_test_pred ,pos_label=1)
rec_score

0.5185185185185185

In the above case we can see that the Recall score is very less , so lets try with Logistic Regression


In [23]:
from sklearn.linear_model  import LogisticRegression
reg_model =LogisticRegression()
reg_model.fit(X_train,Y_train)
reg_Y_train_pred = reg_model.predict(X_train)
reg_Y_test_pred = reg_model.predict(X_test)

In [27]:
#Accuracy score
print(reg_model.score(X_train,Y_train))
print(reg_model.score(X_test,Y_test))

0.7829232995658466
0.7662337662337663


In [30]:
#Recall score for Regression
print('Training recall score:',recall_score(Y_train,reg_Y_train_pred,pos_label= 1))
print('Testing recall score:',recall_score(Y_test,reg_Y_test_pred,pos_label= 1))


Training recall score: 0.5809128630705395
Testing recall score: 0.5185185185185185


In [57]:
#There was not much of a difference in the Recall score

#So testing the SVM model
input_data =[2,197,70,45,543,30.5,0.158,53]
scaled_input_data = sc.transform([input_data]) #transoforms into 2 d array or you can use array and reshape it to[1,-1]
scaled_input_data


array([[2.00e+00, 1.97e+02, 7.00e+01, 4.50e+01, 5.43e+02, 3.05e+01,
        1.58e-01, 5.30e+01]])

In [61]:
svm_model.predict(scaled_input_data)

array([1])

In [63]:
input_data_2 =[1,89,66,23,94,28.1,0.167,21]

In [71]:
reshaped_data = np.asarray(input_data_2).reshape(1,-1)
reshaped_data


array([[ 1.   , 89.   , 66.   , 23.   , 94.   , 28.1  ,  0.167, 21.   ]])

In [74]:
sc.fit(X_train)
trans =sc.transform(reshaped_data)
trans

array([[ 1.0023517 , 87.51794891, 64.79266771, 23.01632229, 92.75116563,
        28.33183481,  0.16629011, 21.24032754]])

In [75]:
svm_model.predict(trans)

array([1])